packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

source "amazon-ebs" "autogenerated_1" {
  ami_name      = "packer-example-${regex_replace(timestamp(), "[^a-zA-Z0-9-]", "")}"
  instance_type = "t2.micro"
  region        = "us-east-1"
  source_ami    = "ami-04b70fa74e45c3917"
  ssh_username  = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    environment_vars = ["DEBIAN_FRONTEND=noninteractive"]
    inline           = ["sudo apt-get update", "sudo apt-get install -y php apache2", "sudo git clone https://github.com/brikis98/php-app.git /var/www/html/app"]
    pause_before     = "1m0s"
  }

}
